"""
Command-line interface for the Python Auto Test Generator.

The CLI orchestrates the complete workflow:
    input validation -> Python file discovery -> test generation -> optional
    pytest/coverage/allure execution -> terminal summary.

It intentionally keeps parsing, heuristic inference, and code generation in their
own modules. This file should coordinate the pipeline, not reimplement it.
"""
from __future__ import annotations

import argparse
import importlib.util
import os
import shutil
import subprocess
import sys
from pathlib import Path
from typing import Any, Dict, Iterable, List, Optional

try:
    from rich.console import Console
    from rich.panel import Panel
    from rich.progress import Progress
    from rich.table import Table

    HAS_RICH = True
except ImportError:  # pragma: no cover - optional presentation dependency
    HAS_RICH = False

from .code_generator import generate_test_file
from .coverage_config import (
    ensure_coverage_config,
    get_coverage_cli_args,
    read_coverage_summary_from_xml,
)

console = Console() if HAS_RICH else None

_EXCLUDED_DIRS = {
    ".git",
    ".hg",
    ".svn",
    ".idea",
    ".vscode",
    ".mypy_cache",
    ".pytest_cache",
    ".ruff_cache",
    "__pycache__",
    ".venv",
    "venv",
    "env",
    "build",
    "dist",
    "htmlcov",
    "allure-results",
    "tests_output",
}

_GENERATED_PATTERNS = (
    "test_*.py",
    "*.pyc",
    ".coverage",
    "coverage.xml",
)


# ============================================================================
# PATH AND FILE DISCOVERY
# ============================================================================

def _as_abs_path(path: str | Path) -> Path:
    return Path(path).expanduser().resolve()


def _is_excluded_dir(path: Path, output_dir: Optional[Path] = None) -> bool:
    if path.name in _EXCLUDED_DIRS:
        return True
    if output_dir is not None:
        try:
            return path.resolve() == output_dir.resolve()
        except Exception:
            return False
    return False


def _is_eligible_python_file(path: Path) -> bool:
    if path.suffix != ".py":
        return False
    if path.name == "__init__.py":
        return False
    if path.name.startswith("test_"):
        return False
    return True


def _collect_python_files(
    input_path: str | Path,
    *,
    recursive: bool = True,
    output_dir: Optional[str | Path] = None,
) -> List[str]:
    """
    Collect eligible Python source files from a file or directory.

    Generated tests, cache folders, virtual environments, reports, and the
    selected output directory are excluded to avoid feeding generated artifacts
    back into the generator.
    """
    path = _as_abs_path(input_path)
    out_path = _as_abs_path(output_dir) if output_dir else None

    if path.is_file():
        return [str(path)] if _is_eligible_python_file(path) else []

    if not path.is_dir():
        return []

    files: List[Path] = []
    if recursive:
        for root, dirs, names in os.walk(path):
            root_path = Path(root)
            dirs[:] = [
                name
                for name in dirs
                if not _is_excluded_dir(root_path / name, out_path)
            ]
            for name in names:
                candidate = root_path / name
                if _is_eligible_python_file(candidate):
                    files.append(candidate.resolve())
    else:
        for candidate in path.iterdir():
            if candidate.is_file() and _is_eligible_python_file(candidate):
                files.append(candidate.resolve())

    return [str(file) for file in sorted(files)]


# ============================================================================
# SAFE OUTPUT CLEANUP
# ============================================================================

def _is_dangerous_output_dir(output_dir: Path, input_path: Path) -> bool:
    """Protect users from accidentally deleting project/root/home folders."""
    output_dir = output_dir.resolve()
    input_path = input_path.resolve()
    home = Path.home().resolve()
    cwd = Path.cwd().resolve()

    dangerous = {home, cwd, Path(output_dir.anchor).resolve()}
    if output_dir in dangerous:
        return True

    if input_path.is_file() and output_dir == input_path.parent.resolve():
        return True
    if input_path.is_dir() and output_dir == input_path:
        return True

    return False


def _remove_path(path: Path) -> None:
    if path.is_file() or path.is_symlink():
        path.unlink()
    elif path.is_dir():
        shutil.rmtree(path)


def _clean_generated_artifacts(output_dir: str | Path) -> None:
    """Remove only files/folders normally generated by this tool."""
    path = _as_abs_path(output_dir)
    if not path.exists():
        return

    for pattern in _GENERATED_PATTERNS:
        for item in path.glob(pattern):
            _remove_path(item)

    for report_dir in ("htmlcov", "allure-results", ".pytest_cache", "__pycache__"):
        item = path / report_dir
        if item.exists():
            _remove_path(item)


def _clean_output_dir(
    output_dir: str | Path,
    *,
    input_path: str | Path,
    clean_all: bool = False,
    no_clean: bool = False,
) -> None:
    path = _as_abs_path(output_dir)
    source = _as_abs_path(input_path)

    if no_clean:
        path.mkdir(parents=True, exist_ok=True)
        return

    if clean_all:
        if _is_dangerous_output_dir(path, source):
            raise ValueError(
                f"Refusing to clean dangerous output directory: {path}. "
                "Choose a dedicated output folder or omit --clean-all."
            )
        if path.exists():
            for item in path.iterdir():
                _remove_path(item)
        path.mkdir(parents=True, exist_ok=True)
        return

    path.mkdir(parents=True, exist_ok=True)
    _clean_generated_artifacts(path)


# ============================================================================
# SUMMARY AND DISPLAY
# ============================================================================

def _count_methods(classes: Iterable[Dict[str, Any]]) -> int:
    return sum(len(cls.get("methods", [])) for cls in classes)


def _count_callables(result: Dict[str, Any]) -> int:
    functions = result.get("functions", [])
    classes = result.get("classes", [])
    return len(functions) + _count_methods(classes)


def _iter_callables(result: Dict[str, Any]) -> Iterable[Dict[str, Any]]:
    for func in result.get("functions", []) or []:
        yield func
    for cls in result.get("classes", []) or []:
        constructor = cls.get("constructor")
        if constructor:
            yield constructor
        for method in cls.get("methods", []) or []:
            yield method


def _count_unresolved_objectives(result: Dict[str, Any]) -> int:
    total = 0
    for func in _iter_callables(result):
        total += len(func.get("unresolved_objectives", []) or [])
    return total


def _pytest_status_label(exit_code: Optional[int]) -> str:
    if exit_code is None:
        return "Not run"
    if exit_code == 0:
        return "Passed"
    if exit_code == 1:
        return "Failed"
    if exit_code == 2:
        return "Interrupted"
    if exit_code == 3:
        return "Internal error"
    if exit_code == 4:
        return "Usage error"
    if exit_code == 5:
        return "No tests collected"
    return f"Exit code {exit_code}"


def _format_percent(value: Any) -> str:
    if value is None:
        return "N/A"
    try:
        return f"{float(value):.2f}%"
    except (TypeError, ValueError):
        return "N/A"


def _coverage_lines(summary: Dict[str, Any]) -> List[tuple[str, Any]]:
    cov = summary.get("coverage_summary") or {}
    if not cov:
        return []

    lines_covered = cov.get("lines_covered")
    lines_valid = cov.get("lines_valid")
    branches_covered = cov.get("branches_covered")
    branches_valid = cov.get("branches_valid")

    rows: List[tuple[str, Any]] = []
    if lines_covered is not None and lines_valid is not None:
        rows.append(("Statements", f"{lines_covered}/{lines_valid}"))
        rows.append(("Missing statements", max(0, int(lines_valid) - int(lines_covered))))
    if branches_covered is not None and branches_valid is not None:
        rows.append(("Branches", f"{branches_covered}/{branches_valid}"))
    if cov.get("line_percent") is not None:
        rows.append(("Statement coverage", _format_percent(cov.get("line_percent"))))
    if cov.get("branch_percent") is not None:
        rows.append(("Branch coverage", _format_percent(cov.get("branch_percent"))))
    return rows


def _callable_signature(func: Dict[str, Any]) -> str:
    args = ", ".join(
        f"{arg['name']}: {arg.get('annotation', 'Any')}"
        for arg in func.get("args", [])
    )
    prefix = "async " if func.get("is_async") else ""
    return f"{prefix}{func['name']}({args}) -> {func.get('return_type', 'Any')}"


def _print_rich_summary(summary: Dict[str, Any], dry_run: bool) -> None:
    """Print the public, white-box-oriented generation summary.

    Deliberately hides internal candidate/discarded counts. The CLI summary is
    meant to communicate the final test suite and coverage verification, not
    implementation telemetry from the selector.
    """
    main_rows: List[tuple[str, Any]] = [
        ("White-box criterion", "Branch/Decision Coverage"),
        ("Input files scanned", summary["scanned_files"]),
        ("Supported callables", summary["supported_callables"]),
        ("Skipped callables", summary["skipped_callables"]),
    ]

    if not dry_run:
        main_rows.extend([
            ("Generated test files", summary["generated_test_files"]),
            ("Generated test cases", summary["generated_test_cases"]),
            ("Unresolved objectives", summary.get("unresolved_objectives", 0)),
        ])

    if summary.get("syntax_error_files"):
        main_rows.append(("Syntax-error files", summary["syntax_error_files"]))
    if summary.get("generation_error_files"):
        main_rows.append(("Generation-error files", summary["generation_error_files"]))

    pytest_exit = summary.get("pytest_exit_code")
    if pytest_exit is not None:
        main_rows.append(("Pytest result", _pytest_status_label(pytest_exit)))
        main_rows.append(("Pytest exit code", pytest_exit))

    coverage_rows = _coverage_lines(summary)

    if not HAS_RICH:
        print("\n============================================================")
        print("AUTO TEST GENERATION SUMMARY")
        print("============================================================")
        for key, value in main_rows:
            print(f"{key:<24}: {value}")
        if coverage_rows:
            print("\nCOVERAGE RESULT")
            print("------------------------------------------------------------")
            for key, value in coverage_rows:
                print(f"{key:<24}: {value}")
        print("============================================================")
        return

    table = Table(title="[bold blue]Auto Test Generation Summary[/bold blue]")
    table.add_column("Metric", style="cyan")
    table.add_column("Value", style="magenta", justify="right")

    for label, value in main_rows:
        table.add_row(label, str(value))

    if coverage_rows:
        table.add_section()
        for label, value in coverage_rows:
            table.add_row(label, str(value))

    console.print(table)

def _print_file_detail(message: str) -> None:
    if HAS_RICH:
        console.print(message)
    else:
        print(message)


def _print_constraints(func: Dict[str, Any], *, verbose: bool) -> None:
    branches = func.get("branches", [])
    if not branches:
        print("      branches: 0")
        return

    print(f"      branches: {len(branches)}")
    for branch in branches:
        source = branch.get("source") or "<condition>"
        line = branch.get("lineno")
        prefix = f"line {line}: " if line else ""
        print(f"        - {prefix}{source}")
        if verbose:
            constraints = branch.get("constraints") or []
            for constraint in constraints:
                arg = constraint.get("arg")
                transform = constraint.get("transform")
                op = constraint.get("op")
                value = constraint.get("value")
                transform_text = f" via {transform}" if transform else ""
                print(f"            constraint: {arg}{transform_text} {op} {value!r}")


def _print_callable_detail(func: Dict[str, Any], *, indent: str = "  ", verbose: bool = False) -> None:
    print(f"{indent}- {_callable_signature(func)}")
    if func.get("method_kind") and func.get("method_kind") != "function":
        print(f"{indent}    method_kind: {func.get('method_kind')}")
    if func.get("unsupported_reasons"):
        print(f"{indent}    unsupported: {', '.join(func.get('unsupported_reasons', []))}")
    elif func.get("unsupported_reason"):
        print(f"{indent}    unsupported: {func.get('unsupported_reason')}")
    else:
        _print_constraints(func, verbose=verbose)
        print(
            f"{indent}    raises: {func.get('raises', False)} / "
            f"unconditional_raise: {func.get('unconditional_raise', False)}"
        )
        if verbose:
            print(f"{indent}    loops: {len(func.get('loops', []))}")
            print(f"{indent}    returns: {len(func.get('returns', []))}")


def _print_dry_run_details(result: Dict[str, Any], *, verbose: bool = False) -> None:
    source_file = result.get("source_file", "<unknown>")
    print(f"\nFile: {source_file}")

    for func in result.get("functions", []):
        _print_callable_detail(func, indent="  ", verbose=verbose)

    for cls in result.get("classes", []):
        print(f"  Class {cls.get('class_name')}")
        constructor = cls.get("constructor")
        if constructor:
            print("    constructor:")
            _print_callable_detail(constructor, indent="      ", verbose=verbose)
        else:
            print("    constructor: none")
        methods = cls.get("methods", [])
        if not methods:
            print("    methods: none")
        for method in methods:
            _print_callable_detail(method, indent="    ", verbose=verbose)


def _update_summary(summary: Dict[str, Any], result: Dict[str, Any], verbose: bool) -> None:
    status = result.get("status")
    skipped = result.get("skipped_functions", []) or result.get("skipped_callables", []) or []
    total_callables = _count_callables(result)

    summary["supported_callables"] += max(0, total_callables - len(skipped))
    summary["skipped_callables"] += len(skipped)
    summary["generated_test_cases"] += result.get("generated_tests", 0)
    summary["unresolved_objectives"] += _count_unresolved_objectives(result)

    if status == "syntax_error":
        summary["syntax_error_files"] += 1
    elif status == "generation_error":
        summary["generation_error_files"] += 1
    elif status == "generated":
        summary["generated_test_files"] += 1

    if verbose:
        source = result.get("source_file", "<unknown>")
        if status == "generated":
            _print_file_detail(f"[OK] {source} -> {result.get('output_file')}")
        elif status == "dry_run":
            _print_file_detail(f"[DRY-RUN] {source}")
        elif status == "syntax_error":
            _print_file_detail(f"[SYNTAX ERROR] {source}: {result.get('message')}")
        elif status == "generation_error":
            _print_file_detail(f"[GENERATION ERROR] {source}: {result.get('message')}")
        elif status == "no_supported_functions":
            _print_file_detail(f"[SKIP] {source}: no supported callables")


# ============================================================================
# PYTEST EXECUTION
# ============================================================================

def _resolve_coverage_target(input_path: str | Path, module_path: Optional[str], cov_target: Optional[str]) -> str:
    if cov_target:
        return cov_target
    if module_path:
        return module_path
    return str(_as_abs_path(input_path))


def _run_pytest(
    test_dir: str,
    *,
    module_path: Optional[str],
    input_path: str,
    use_cov: bool = False,
    cov_target: Optional[str] = None,
    use_allure: bool = False,
) -> int:
    if HAS_RICH:
        console.print(Panel(f"[bold green]Running pytest on {test_dir}...[/bold green]"))
    else:
        print(f"\nRunning pytest on {test_dir}...")

    cmd = [
        sys.executable,
        "-m",
        "pytest",
        test_dir,
        "-v",
        "-p",
        "no:html",
        "-p",
        "no:jsonreport",
    ]

    if use_cov:
        target = _resolve_coverage_target(input_path, module_path, cov_target)
        source_path = _as_abs_path(input_path)
        coverage_root_hint = source_path if source_path.is_dir() else source_path.parent
        try:
            coveragerc_path = ensure_coverage_config(coverage_root_hint)
            cmd.extend(
                get_coverage_cli_args(
                    coverage_target=target,
                    include_branch=True,
                    include_term=True,
                    include_html=True,
                    include_xml=True,
                    include_json=False,
                    project_root=coverage_root_hint,
                    config_path=coveragerc_path,
                )
            )
        except Exception as exc:
            if HAS_RICH:
                console.print(f"[bold red]Coverage configuration error:[/bold red] {exc}")
            else:
                print(f"Coverage configuration error: {exc}")
            return 2

    allure_dir = "allure-results"
    if use_allure:
        cmd.append(f"--alluredir={allure_dir}")

    env = os.environ.copy()
    current_pp = env.get("PYTHONPATH", "")
    source_path = _as_abs_path(input_path)
    additional_path = source_path if source_path.is_dir() else source_path.parent
    env["PYTHONPATH"] = (
        f"{additional_path}{os.pathsep}{current_pp}" if current_pp else str(additional_path)
    )

    try:
        completed = subprocess.run(cmd, check=False, env=env)
    except Exception as exc:
        if HAS_RICH:
            console.print(f"[bold red]Error during test execution:[/bold red] {exc}")
        else:
            print(f"Error during test execution: {exc}")
        return 2

    if use_allure:
        if HAS_RICH:
            console.print(f"\n[bold blue]Allure results saved to '{allure_dir}'.[/bold blue]")
            console.print("[bold blue]To view the report, run:[/bold blue] allure serve allure-results")
        else:
            print(f"\nAllure results saved to '{allure_dir}'.")
            print("To view the report, run: allure serve allure-results")

    return completed.returncode


# ============================================================================
# ARGUMENT PARSING AND MAIN WORKFLOW
# ============================================================================

def _build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description="Auto Test Generator - AST-based Static Analysis Tool"
    )
    parser.add_argument("input", help="A Python file or directory of Python files.")
    parser.add_argument(
        "--out",
        "-o",
        default="tests_output",
        help="Directory where generated pytest files will be written.",
    )
    parser.add_argument(
        "--module",
        "-m",
        help="Optional import prefix/package path for generated imports.",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Parse files and print extracted metadata without writing files.",
    )
    parser.add_argument(
        "--verbose",
        "-v",
        action="store_true",
        help="Print per-file processing details.",
    )
    parser.add_argument(
        "--run",
        action="store_true",
        help="Run pytest immediately after generation.",
    )
    parser.add_argument(
        "--cov",
        action="store_true",
        help="Run pytest with coverage report. Requires --run and pytest-cov.",
    )
    parser.add_argument(
        "--cov-target",
        help="Explicit coverage target path/module. Defaults to input path or --module.",
    )
    parser.add_argument(
        "--allure",
        action="store_true",
        help="Generate Allure-compatible tests and run pytest with --alluredir. Requires --run and allure-pytest.",
    )
    parser.add_argument(
        "--no-recursive",
        action="store_true",
        help="When input is a directory, scan only the first level.",
    )
    parser.add_argument(
        "--no-clean",
        action="store_true",
        help="Do not clean generated artifacts in the output directory before generation.",
    )
    parser.add_argument(
        "--clean-all",
        action="store_true",
        help="Delete all contents of the output directory before generation. Refuses dangerous paths.",
    )
    return parser


def _validate_args(parser: argparse.ArgumentParser, args: argparse.Namespace) -> None:
    if args.cov and not args.run:
        parser.error("--cov requires --run")
    if args.cov_target and not args.cov:
        parser.error("--cov-target requires --cov")
    if args.allure and not args.run:
        parser.error("--allure requires --run")
    if args.dry_run and args.run:
        parser.error("--dry-run cannot be combined with --run")
    if args.no_clean and args.clean_all:
        parser.error("--no-clean and --clean-all cannot be used together")
    if args.cov and importlib.util.find_spec("pytest_cov") is None:
        parser.error("--cov requires pytest-cov to be installed")
    if args.allure and importlib.util.find_spec("allure") is None:
        parser.error("--allure requires allure-pytest to be installed")


def _generate_for_file(
    file_path: str,
    args: argparse.Namespace,
) -> Dict[str, Any]:
    try:
        return generate_test_file(
            file_path,
            args.out,
            module_path=args.module,
            dry_run=args.dry_run,
            use_allure=args.allure,
        )
    except Exception as exc:
        return {
            "status": "generation_error",
            "source_file": file_path,
            "message": f"{type(exc).__name__}: {exc}",
            "functions": [],
            "classes": [],
            "generated_tests": 0,
            "output_file": None,
            "skipped_functions": [],
        }


def main() -> None:
    parser = _build_parser()
    args = parser.parse_args()
    _validate_args(parser, args)

    input_path = _as_abs_path(args.input)
    if not input_path.exists():
        print(f"Error: path does not exist -> {args.input}")
        sys.exit(1)

    files = _collect_python_files(
        input_path,
        recursive=not args.no_recursive,
        output_dir=args.out,
    )
    if not files:
        print("Error: no eligible Python source files were found.")
        sys.exit(1)

    summary: Dict[str, Any] = {
        "scanned_files": len(files),
        "generated_test_files": 0,
        "syntax_error_files": 0,
        "generation_error_files": 0,
        "supported_callables": 0,
        "skipped_callables": 0,
        "generated_test_cases": 0,
        "unresolved_objectives": 0,
        "pytest_exit_code": None,
        "coverage_summary": {},
    }

    if not args.dry_run:
        try:
            _clean_output_dir(
                args.out,
                input_path=input_path,
                clean_all=args.clean_all,
                no_clean=args.no_clean,
            )
        except ValueError as exc:
            print(f"Error: {exc}")
            sys.exit(1)

    if HAS_RICH and not args.dry_run:
        with Progress() as progress:
            task = progress.add_task("[green]Generating tests...", total=len(files))
            for file_path in files:
                result = _generate_for_file(file_path, args)
                _update_summary(summary, result, args.verbose)
                progress.update(task, advance=1)
    else:
        for file_path in files:
            if args.verbose:
                mode = "DRY-RUN" if args.dry_run else "GENERATE"
                print(f"[{mode}] {file_path}")
            result = _generate_for_file(file_path, args)
            _update_summary(summary, result, args.verbose)
            if args.dry_run:
                _print_dry_run_details(result, verbose=args.verbose)

    pytest_exit_code: Optional[int] = None
    if args.run and not args.dry_run:
        pytest_exit_code = _run_pytest(
            args.out,
            module_path=args.module,
            input_path=args.input,
            use_cov=args.cov,
            cov_target=args.cov_target,
            use_allure=args.allure,
        )
        summary["pytest_exit_code"] = pytest_exit_code
        if args.cov:
            summary["coverage_summary"] = read_coverage_summary_from_xml("coverage.xml")

    _print_rich_summary(summary, args.dry_run)

    if pytest_exit_code is not None:
        sys.exit(pytest_exit_code)
    if summary["syntax_error_files"] or summary["generation_error_files"]:
        sys.exit(1)
    sys.exit(0)


if __name__ == "__main__":
    main()
